# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: task03 create publish release PowerCollections

on:
  workflow_dispatch:

jobs:
  task03_nuget:

    runs-on: windows-latest
    
    permissions: write-all

    steps:
    
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: create
      run: dotnet pack 
      working-directory: PowerCollections
      
    - name: publish
      run: dotnet nuget push "PowerCollections\PowerCollections\bin\Debug\*.nupkg" -k ${{secrets.GITHUB_TOKEN}} -s https://nuget.pkg.github.com/Tikayyy/index.json --skip-duplicate
      
    - name: Get XML Info
      id: xml
      uses: mavrosxristoforos/get-xml-info@1.1.1
      with:
        xml-file: 'PowerCollections\PowerCollections\PowerCollections.csproj'
        xpath: '//Version'

    - name: release
      uses: ncipollo/release-action@v1.12.0
      with:
        tag: 'v${{ steps.xml.outputs.info }}'
        artifacts: 'PowerCollections\PowerCollections\bin\Debug\Tikayyy.PowerCollections.${{ steps.xml.outputs.info }}.nupkg'
        
